[build]
  base    = "project"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  # ① まず、assets 配下へのリクエストはそのまま返す
  from   = "/assets/*"
  to     = "/assets/:splat"
  status = 200

[[redirects]]
  # ② 上記以外（例：/about や /contact など）はすべて index.html に返す
  from   = "/*"
  to     = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://images.pexels.com data:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
  # （必要に応じてヘッダー設定がある場合はそのまま）
  
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript" 